### ISSUE TITLE
Fix: Handle Ctrl-C or exit gracefully after OpenAI API interaction

### ISSUE THREAD

**Issue by kordless** [MittaAI/webwright#9]
### Description
When attempting to interrupt (Ctrl-C) or exit the application after interacting with the OpenAI API, a messy error is thrown. This needs to be handled gracefully.

### Steps to Reproduce
1. Interact with the OpenAI API in the application.
2. Attempt to interrupt or exit the application using Ctrl-C.
3. Observe the messy error output.

### Expected Behavior
The application should handle the situation gracefully, ensuring that any necessary cleanup is performed and no error messages are displayed.

### Suggested Fix
Implement a signal handler for SIGINT (Ctrl-C) that safely exits the application without throwing errors. Ensure that any resources are properly cleaned up before exiting.

### Additional Information
- Ensure compatibility with other parts of the application that may also handle signals.
- Test on different operating systems to ensure consistent behavior.

**Comment by kordless** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\kord\miniconda3\envs\webwright\Scripts\webwright-script.py", line 33, in <module>
    sys.exit(load_entry_point('webwright', 'console_scripts', 'webwright')())
  File "c:\users\kord\code\mitta\webwright\webwright\main.py", line 240, in entry_point
    tasks = [task for task in asyncio.all_tasks() if not task.done()]
  File "C:\Users\kord\miniconda3\envs\webwright\lib\asyncio\tasks.py", line 44, in all_tasks
    loop = events.get_running_loop()
RuntimeError: no running event loop
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002A84F718280>
Traceback (most recent call last):
  File "C:\Users\kord\miniconda3\envs\webwright\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\kord\miniconda3\envs\webwright\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\kord\miniconda3\envs\webwright\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\kord\miniconda3\envs\webwright\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
